FROM mcr.microsoft.com/dotnet/sdk:3.1
WORKDIR /src

COPY Bookshelf.Core/Bookshelf.Core.csproj Bookshelf.Core/
RUN dotnet restore Bookshelf.Core/Bookshelf.Core.csproj

WORKDIR /src/Bookshelf.Core
EXPOSE 8080

CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080"]
